import ourl from "../assets/omnifood.jpg";
import furl from "../assets/furniture.jpg";
import purl from "../assets/portfolio.jpg";

const ProjectSec = ({ project }) => {
  return (
    <div>
      <a href={project.link} className="project-title">
        {project.title}
      </a>
      <p className="project-desc">{project.desc}</p>
      <ul className="flex mt-3 gap-x-4">
        {project.languages.map((lang) => (
          <li className="inline-block proj-tag" key={lang}>
            {lang}
          </li>
        ))}
      </ul>
    </div>
  );
};
export default function Project() {
  return (
    <section className="bg-tertiary">
      <div className="container !pt-24" id="project">
        <section className="mb-24 text-center">
          <h1 className="main-head">Project</h1>
          <p className="text-xl">
            Here you will find some of the projects that I built in my free
            time.
          </p>
        </section>
        <section className="grid items-center justify-between grid-cols-1 lg:grid-cols-2 gap-x-48 gap-y-12">
          <ProjectSec project={projects[0]} />
          <img src={ourl} alt="woman eating food" className="row-end-1 lg:row-end-auto project-img" />
          <img src={furl} alt="chairs" className="project-img" />
          <ProjectSec project={projects[1]} />
          <ProjectSec project={projects[2]} />
          <img src={purl} alt="user description" className="row-end-5 project-img lg:row-end-auto" />
        </section>
      </div>
    </section>
  );
}

const projects = [
  {
    title: "Omnifood",
    link: "https://ps-omnifood.netlify.app/",
    desc: "Omnifood is an web app through which you can order an online healthy meal, diets are generated by AI powered. For now it is a static website, coded in pure html and css with some tints of Java Script. Designed by Udemy instructor Jonas, I built this project during online course.",
    languages: ["html", "css", "java script"],
  },
  {
    title: "Furniture",
    link: "#",
    desc: "Furniture is a website, meant to display the wooden furnitures along with price tags. People can visit and order the furniture based on their preferences. Right now it is static coded with pure HTML and CSS. Built during my online course",
    languages: ["html", "css"],
  },
  {
    title: "portfolio",
    link: "https://phurbasherpa.netlify.app",
    desc: "A personal website to showcase your work. Loosely designed in Figma and coded in Visual Studio Code by yours truly. Built with React.js and Tailwind CSS, deployed with Netlify. All text is set in the Inter typeface.",
    languages: ["react js", "tailwind css", "vite"],
  },
];
